import React from "react";
import Head from "next/head";
import Nav from "../components/nav";
import Footer from "@/components/Footer";
import { useRouter } from "next/router";
import BuyMeACoffee from "@/components/BuyMeACoffee";

export default function Home() {
  const router = useRouter();

  const navigateToExercise = (path) => {
    router.push(path);
  };

  return (
    <>
      <Head>
        <title>Breathe-Ease</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <div className="container mx-auto">
        <h1 className="text-center text-4xl mt-12 mb-6">
          Select a Breathing Technique
        </h1>
        <div className="flex justify-center">
          <button
            onClick={() => navigateToExercise("/four-seven-eight")}
            className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded mr-4"
          >
            4-7-8 Breathing Technique
          </button>
          <button
            onClick={() => navigateToExercise("/four-four-four")}
            className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded"
          >
            4-4-4 Box Breathing Technique
          </button>
        </div>
        <BuyMeACoffee />
      </div>

      <Footer />
    </>
  );
}
